-- MySQL Script generated by MySQL Workbench
-- Thu May  1 19:04:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema checktec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema checktec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checktec` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `checktec` ;

-- -----------------------------------------------------
-- Table `checktec`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checktec`.`Alumno` (
  `id_Alumno` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido_paterna` VARCHAR(20) NOT NULL,
  `Apellido_materno` VARCHAR(20) NOT NULL,
  `No_Control` INT NOT NULL,
  `Carrera` ENUM('Sistemas', 'Mecatrónica', 'Mecánica', 'Civil', 'Alimentarias', 'Electrónica', 'Industrial', 'Administración', 'Agricola') NOT NULL,
  `Semestre` ENUM('Primero', 'Segundo', 'Tercero', 'Cuarto', 'Quinto', 'Sexto', 'Séptimo', 'Octavo', 'Noveno', 'Décimo') NOT NULL,
  `Correo` VARCHAR(45) NULL DEFAULT NULL,
  `Teléfono` VARCHAR(15) NULL DEFAULT NULL,
  `estatus_beca` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_Alumno`),
  UNIQUE INDEX `No_Control_UNIQUE` (`No_Control` ASC) VISIBLE,
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  UNIQUE INDEX `Teléfono_UNIQUE` (`Teléfono` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `checktec`.`Cafeteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checktec`.`Cafeteria` (
  `id_Cafeteria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(1) NOT NULL,
  `Capacidad` INT NOT NULL,
  PRIMARY KEY (`id_Cafeteria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checktec`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checktec`.`Asistencia` (
  `id_Asistencia` INT NOT NULL AUTO_INCREMENT,
  `id_Alumno` INT NOT NULL,
  `id_Cafeteria` INT NOT NULL,
  `Fecha_Asistencia` DATETIME NOT NULL,
  `Alumno_id_Alumno` INT NOT NULL,
  `Cafeteria_id_Cafeteria` INT NOT NULL,
  PRIMARY KEY (`id_Asistencia`, `Alumno_id_Alumno`, `Cafeteria_id_Cafeteria`),
  INDEX `fk_Asistencia_Alumno_idx` (`Alumno_id_Alumno` ASC) VISIBLE,
  INDEX `fk_Asistencia_Cafeteria1_idx` (`Cafeteria_id_Cafeteria` ASC) VISIBLE,
  CONSTRAINT `fk_Asistencia_Alumno`
    FOREIGN KEY (`Alumno_id_Alumno`)
    REFERENCES `checktec`.`Alumno` (`id_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistencia_Cafeteria1`
    FOREIGN KEY (`Cafeteria_id_Cafeteria`)
    REFERENCES `checktec`.`Cafeteria` (`id_Cafeteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checktec`.`Huella`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checktec`.`Huella` (
  `id_Huella` INT NOT NULL AUTO_INCREMENT,
  `id_Alumno` INT NOT NULL,
  `Template` BLOB NOT NULL,
  `Fecha_registro` DATETIME NOT NULL,
  `Alumno_id_Alumno` INT NOT NULL,
  PRIMARY KEY (`id_Huella`, `Alumno_id_Alumno`),
  INDEX `fk_Huella_Alumno1_idx` (`Alumno_id_Alumno` ASC) VISIBLE,
  CONSTRAINT `fk_Huella_Alumno1`
    FOREIGN KEY (`Alumno_id_Alumno`)
    REFERENCES `checktec`.`Alumno` (`id_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checktec`.`Registrar_Cambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checktec`.`Registrar_Cambio` (
  `id_Registrar_Cambio` INT NOT NULL AUTO_INCREMENT,
  `id_Usuario` INT NOT NULL,
  `Tabla_afectada` VARCHAR(45) NOT NULL,
  `Tipo_accion` ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  `Fecha_hora_cambio` DATETIME NOT NULL,
  `Detalle_cambio` TEXT(200) NULL,
  PRIMARY KEY (`id_Registrar_Cambio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checktec`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checktec`.`Usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido_paterno` VARCHAR(20) NOT NULL,
  `Apellido_materno` VARCHAR(20) NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(30) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `Rol` ENUM('Admin', 'Miembro_CESA') NOT NULL,
  `Ultimo_acceso` DATETIME NOT NULL,
  `Registrar_Cambio_id_Registrar_Cambio` INT NOT NULL,
  PRIMARY KEY (`id_Usuario`, `Registrar_Cambio_id_Registrar_Cambio`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Registrar_Cambio1_idx` (`Registrar_Cambio_id_Registrar_Cambio` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Registrar_Cambio1`
    FOREIGN KEY (`Registrar_Cambio_id_Registrar_Cambio`)
    REFERENCES `checktec`.`Registrar_Cambio` (`id_Registrar_Cambio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
