-- MySQL Script generated by MySQL Workbench
-- Thu May  1 23:06:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema checktec
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `checktec` ;

-- -----------------------------------------------------
-- Schema checktec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checktec` DEFAULT CHARACTER SET utf8 ;
USE `checktec` ;

-- -----------------------------------------------------
-- Table `checktec`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checktec`.`alumno` ;

CREATE TABLE IF NOT EXISTS `checktec`.`alumno` (
  `id_Alumno` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido_paterno` VARCHAR(20) NOT NULL,
  `Apellido_materno` VARCHAR(20) NOT NULL,
  `No_Control` INT(11) NOT NULL,
  `Carrera` ENUM('Sistemas', 'Mecatrónica', 'Mecánica', 'Civil', 'Alimentarias', 'Electrónica', 'Industrial', 'Administración', 'Agricola') NOT NULL,
  `Semestre` ENUM('Primero', 'Segundo', 'Tercero', 'Cuarto', 'Quinto', 'Sexto', 'Séptimo', 'Octavo', 'Noveno', 'Décimo') NOT NULL,
  `Correo` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` VARCHAR(15) NULL DEFAULT NULL,
  `estatus_beca` TINYINT(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_Alumno`),
  UNIQUE INDEX `No_Control_UNIQUE` (`No_Control` ASC),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `checktec`.`cafeteria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checktec`.`cafeteria` ;

CREATE TABLE IF NOT EXISTS `checktec`.`cafeteria` (
  `id_Cafeteria` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(1) NOT NULL,
  `Capacidad` INT(11) NOT NULL,
  PRIMARY KEY (`id_Cafeteria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `checktec`.`asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checktec`.`asistencia` ;

CREATE TABLE IF NOT EXISTS `checktec`.`asistencia` (
  `id_Asistencia` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha_asistencia` DATETIME NOT NULL,
  `id_Alumno` INT(11) NOT NULL,
  `id_Cafeteria` INT(11) NOT NULL,
  PRIMARY KEY (`id_Asistencia`, `id_Alumno`, `id_Cafeteria`),
  INDEX `fk_Asistencia_Alumno_idx` (`id_Alumno` ASC),
  INDEX `fk_Asistencia_Cafeteria1_idx` (`id_Cafeteria` ASC),
  CONSTRAINT `fk_Asistencia_Alumno`
    FOREIGN KEY (`id_Alumno`)
    REFERENCES `checktec`.`alumno` (`id_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistencia_Cafeteria1`
    FOREIGN KEY (`id_Cafeteria`)
    REFERENCES `checktec`.`cafeteria` (`id_Cafeteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `checktec`.`huella`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checktec`.`huella` ;

CREATE TABLE IF NOT EXISTS `checktec`.`huella` (
  `id_Huella` INT(11) NOT NULL AUTO_INCREMENT,
  `Data` BLOB NOT NULL,
  `Fecha_registro` DATETIME NOT NULL,
  `id_Alumno` INT(11) NOT NULL,
  PRIMARY KEY (`id_Huella`, `id_Alumno`),
  INDEX `fk_Huella_Alumno1_idx` (`id_Alumno` ASC),
  CONSTRAINT `fk_Huella_Alumno1`
    FOREIGN KEY (`id_Alumno`)
    REFERENCES `checktec`.`alumno` (`id_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `checktec`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checktec`.`usuario` ;

CREATE TABLE IF NOT EXISTS `checktec`.`usuario` (
  `id_Usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellido_paterno` VARCHAR(20) NOT NULL,
  `Apellido_materno` VARCHAR(20) NULL DEFAULT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(30) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `Rol` ENUM('Admin', 'Miembro_CESA') NOT NULL,
  `Ultimo_acceso` DATETIME NOT NULL,
  PRIMARY KEY (`id_Usuario`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `checktec`.`accion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checktec`.`accion` ;

CREATE TABLE IF NOT EXISTS `checktec`.`accion` (
  `id_Accion` INT(11) NOT NULL AUTO_INCREMENT,
  `Tabla_afectada` VARCHAR(45) NOT NULL,
  `Tipo_accion` ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  `Fecha_cambio` DATETIME NOT NULL,
  `Detalle_cambio` TEXT NULL DEFAULT NULL,
  `id_Usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_Accion`),
  INDEX `fk_Accion_usuario1_idx` (`id_Usuario` ASC),
  CONSTRAINT `fk_Accion_usuario1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `checktec`.`usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
